name: Swift

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

language: swift
osx_image: xcode12.5

env:
  matrix:
   - DESTINATION="platform=iOS Simulator,OS=14.5,name=iPhone X"

before_script: cd Texstyle

script:
   - xcodebuild clean test -project Texstyle.xcodeproj -scheme Texstyle -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
   
after_success:
  - bash <(curl -s https://codecov.io/bash)
